# Generated by Django 2.2.3 on 2019-07-21 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('todo', models.CharField(choices=[('사료', '사료'), ('산책', '산책'), ('쇼핑', '쇼핑'), ('병원', '병원'), ('목욕', '목욕')], default='사료', max_length=4)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 21, 22, 44, 37, 202414))),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 21, 22, 44, 37, 202414))),
            ],
        ),
    ]
