# Generated by Django 2.2.4 on 2019-08-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='event',
            name='todo',
            field=models.CharField(choices=[('사료', '사료'), ('산책', '산책'), ('쇼핑', '쇼핑'), ('병원', '병원'), ('목욕', '목욕'), ('기타', '기타')], default='사료', max_length=5),
        ),
    ]
