# Generated by Django 2.2.3 on 2019-07-20 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 20, 15, 24, 50, 460107)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 20, 15, 24, 50, 460107)),
        ),
        migrations.AlterField(
            model_name='event',
            name='todo',
            field=models.CharField(choices=[('사료', '사료'), ('산책', '산책'), ('쇼핑', '쇼핑'), ('병원', '병원'), ('목욕', '목욕')], default='사료', max_length=4),
        ),
    ]
