# Generated by Django 2.2.3 on 2019-07-23 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_auto_20190723_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 23, 0, 13, 44, 118272)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 23, 0, 13, 44, 118272)),
        ),
    ]
