# Generated by Django 2.2.3 on 2019-07-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Board',
        ),
    ]
