# Generated by Django 2.2.3 on 2019-07-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='board',
            new_name='title',
        ),
    ]
