# Generated by Django 2.2.3 on 2019-07-30 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='like',
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.FileField(default='https://image.flaticon.com/icons/svg/149/149852.svg', upload_to='images/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_body', models.CharField(max_length=50)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Board')),
            ],
        ),
    ]
