# Generated by Django 2.2.3 on 2019-08-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='board',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
