# Generated by Django 2.2.3 on 2019-07-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190719_1921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Posting',
        ),
    ]
