# Generated by Django 2.2.3 on 2019-07-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20190719_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='image',
            field=models.FileField(default='C:\\Github\\dangdangs\\media\\images\\dog2.png', upload_to='board/%Y/%m/%d'),
        ),
    ]
